---
# Source: snowdrop-bot/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snowdrop-bot
  labels:
    helm.sh/chart: snowdrop-bot-0.1.0
    app.kubernetes.io/name: snowdrop-bot
    app.kubernetes.io/instance: snowdrop-bot
    app.kubernetes.io/managed-by: Helm
