apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "snowdrop-bot.pvcName" . }}
  labels:
  {{- include "snowdrop-bot.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem