apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "snowdrop-bot.name" . }}-github"
  labels:
  {{- include "snowdrop-bot.labels" . | nindent 4 }}
type: Opaque
data:
  GITHUB_TOKEN: {{ required "A value must be entered for github.token" .Values.secret.github.token | b64enc | quote }}
  github.users: {{ .Values.secret.github.associates | b64enc | quote }}